blank_issues_enabled: false
contact_links:
  - name: NEN 2660 Community Forum (test)
    url: https://github.com/nl-digigo/nen2660/discussions/
    about: Ask questions and discuss the standard here.
